dzdzdz

diff --git a/.github/workflows/export_csv_stats.yml b/.github/workflows/export_csv_stats.yml
--- a/.github/workflows/export_csv_stats.yml
+++ b/.github/workflows/export_csv_stats.yml
@@ -21,10 +21,36 @@ jobs:
     - name: Get specific workflow run ID
       id: get-specific-run-id
       run: |
-        # Fetch the workflow runs and find the run with the specified name
-        run_id=$(gh api -X GET /repos/${{ github.repository }}/actions/runs | jq -r --arg name "Release" '.workflow_runs[] | select(.name == $name) | .id')
+        # Initialize variables
+        page=1
+        per_page=100
+        run_id=""
+        run_name="${{ github.event.inputs.run_name }}"
+        
+        while [ -z "$run_id" ]; do
+          # Fetch the current page of workflow runs
+          response=$(gh api -X GET "/repos/${{ github.repository }}/actions/runs?per_page=$per_page&page=$page")
+          
+          # Check if there are any runs
+          if [ "$(echo "$response" | jq '.workflow_runs | length')" -eq 0 ]; then
+            echo "No more runs found."
+            break
+          fi
+
+          # Search for the run with the specified name
+          run_id=$(echo "$response" | jq -r --arg name "$run_name" '.workflow_runs[] | select(.name == $name) | .id')
+
+          # Increment page number
+          page=$((page + 1))
+        done
+
+        if [ -z "$run_id" ]; then
+          echo "Run with name '$run_name' not found."
+          exit 1
+        fi
+
         echo "run_id=$run_id" >> $GITHUB_ENV
-        echo "run_id=$run_id"
+        echo "Run ID: $run_id"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
